# -*- coding: utf-8 -*-
"""8 variações de vídeo sobre Lucia & Jason (GTA 6), cada uma com curiosidades diferentes."""

IMG = {
    "lucia_din": "images/user/GTA6_Lucia_Dinheiro_01.png",
    "lucia_tre": "images/user/GTA6_Lucia_Treino_01.png",
    "jason_car": "images/user/GTA6_Jason_Carro_01.png",
    "jason_cel": "images/user/GTA6_Jason_Celular_01.png",
    "danca":     "images/user/GTA6_Jason_Lucia_Danca_01.png",
    "danca_n":   "images/user/GTA6_Jason_Lucia_Danca_Noite_01.png",
    "noite":     "images/user/GTA6_Jason_Lucia_Noite_01.png",
    "assalto":   "images/user/GTA6_Lucia_Jason_Assalto_01.png",
    "keys":      "images/user/GTA6_Leonida_Keys_01.png",
    "vc_noite":  "images/user/GTA6_Vice_City_Noite_01.png",
}

# moves ciclam para dar variedade ao Ken Burns
MOVES = ["in", "punch", "left", "right", "diag", "diag2", "up", "down", "in_slow"]

VARIATIONS = [
{
    "slug": "quem_e_lucia",
    "title_hook": "QUEM É LUCIA?",
    "cta": ("LUCIA OU JASON?", "COMENTA!"),
    "segments": [
        {"kind": "hook", "narration": "Você acha que conhece a Lucia de GTA 6? Espera só até ver essas curiosidades sobre ela!",
         "captions": ["Você conhece", "a *LUCIA* de *GTA 6*?", "olha essas *CURIOSIDADES!*"], "image": "vc_noite"},
        {"kind": "fact", "title": "PRIMEIRA PROTAGONISTA FEMININA",
         "narration": "Lucia é a primeira protagonista feminina de destaque da história da franquia principal GTA.",
         "captions": ["*LUCIA* é a *PRIMEIRA*", "protagonista *FEMININA*", "de *DESTAQUE* na franquia *GTA*"], "image": "lucia_din"},
        {"kind": "fact", "title": "RAÍZES EM LIBERTY CITY",
         "narration": "Ela cresceu em Liberty City, a versão da Rockstar pra Nova York, antes de ir parar em Leonida.",
         "captions": ["Ela cresceu em", "*LIBERTY CITY*", "a *NOVA YORK* da *ROCKSTAR*"], "image": "vc_noite"},
        {"kind": "fact", "title": "LUTA DESDE CRIANÇA",
         "narration": "O pai de Lucia ensinou ela a lutar desde que aprendeu a andar. Isso mesmo, literalmente.",
         "captions": ["O *PAI* dela", "ensinou a *LUTAR*", "desde que aprendeu", "a *ANDAR*"], "image": "lucia_tre"},
        {"kind": "fact", "title": "PRESA PELA FAMÍLIA",
         "narration": "Lutando pela família, ela acabou presa na Penitenciária de Leonida.",
         "captions": ["Lutando pela *FAMÍLIA*", "ela foi parar na", "Penitenciária de *LEONIDA*"], "image": "lucia_din"},
        {"kind": "fact", "title": "\"MÁ SORTE, EU ACHO\"",
         "narration": "Na audiência de condicional do trailer, ela diz apenas: má sorte, eu acho.",
         "captions": ["No trailer, ela diz só:", "\"*MÁ SORTE*...", "*EU ACHO*.\""], "image": "lucia_din"},
        {"kind": "fact", "title": "PURA SORTE",
         "narration": "Segundo a Rockstar, ela saiu da prisão por pura sorte.",
         "captions": ["Ela saiu da prisão", "por *PURA SORTE*", "segundo a *ROCKSTAR*"], "image": "noite"},
        {"kind": "fact", "title": "O SONHO DA MÃE",
         "narration": "O sonho dela é a vida boa que a mãe sempre quis, desde os tempos de Liberty City.",
         "captions": ["O sonho dela?", "a *VIDA BOA*", "que a *MÃE*", "sempre *QUIS*"], "image": "lucia_din"},
        {"kind": "cta", "narration": "E aí, Lucia ou Jason? Comenta aqui embaixo quem você quer jogar primeiro!",
         "captions": ["*LUCIA* ou *JASON*?", "quem você quer", "jogar *PRIMEIRO*?"], "image": "noite"},
    ],
},
{
    "slug": "quem_e_jason",
    "title_hook": "QUEM É JASON?",
    "cta": ("TIME JASON?", "COMENTA!"),
    "segments": [
        {"kind": "hook", "narration": "A Lucia todo mundo já conhece. Mas e o Jason de GTA 6? Bora descobrir quem ele é!",
         "captions": ["Você conhece o", "*JASON* de *GTA 6*?", "olha essas *CURIOSIDADES!*"], "image": "jason_car"},
        {"kind": "fact", "title": "VIDA FÁCIL? NEM TANTO",
         "narration": "Jason Duval só quer uma vida fácil. Só que as coisas insistem em ficar mais difíceis.",
         "captions": ["*JASON* quer uma", "*VIDA FÁCIL*...", "mas as coisas", "só *PIORAM*"], "image": "jason_car"},
        {"kind": "fact", "title": "CRESCEU NO CRIME",
         "narration": "Ele cresceu cercado de trambiqueiros e criminosos no estado de Leonida.",
         "captions": ["Ele cresceu", "cercado de", "*TRAMBIQUEIROS*", "e *CRIMINOSOS*"], "image": "jason_car"},
        {"kind": "fact", "title": "PASSAGEM PELO EXÉRCITO",
         "narration": "Pra fugir da adolescência complicada, ele serviu no exército americano.",
         "captions": ["Pra fugir da", "*ADOLESCÊNCIA*", "ele serviu no", "*EXÉRCITO*"], "image": "jason_cel"},
        {"kind": "fact", "title": "TRÁFICO NAS KEYS",
         "narration": "Depois do exército, foi parar nas Keys, trabalhando pra traficantes locais.",
         "captions": ["Depois do *EXÉRCITO*", "foi trabalhar pra", "*TRAFICANTES*", "nas *KEYS*"], "image": "keys"},
        {"kind": "fact", "title": "PALAFITA EM KEY LENTO",
         "narration": "A casa dele é uma palafita em Key Lento, cedida por um chefão do tráfico da região.",
         "captions": ["A casa dele é uma", "*PALAFITA* em *KEY LENTO*", "cedida por um", "*CHEFÃO* local"], "image": "keys"},
        {"kind": "fact", "title": "\"MAIS UM DIA NO PARAÍSO\"",
         "narration": "A frase de Jason no jogo? Mais um dia no paraíso, né?",
         "captions": ["A frase dele:", "\"*MAIS UM DIA*", "no *PARAÍSO*, né?\""], "image": "jason_cel"},
        {"kind": "fact", "title": "LUCIA: SORTE OU AZAR?",
         "narration": "Conhecer a Lucia pode ser a melhor ou a pior coisa que já aconteceu com ele. Difícil saber.",
         "captions": ["Conhecer *LUCIA*", "pode ser a *MELHOR*", "ou a *PIOR* coisa", "da vida *DELE*"], "image": "noite"},
        {"kind": "cta", "narration": "Time Jason ou time Lucia? Diz aí nos comentários qual você acha mais daora!",
         "captions": ["*TIME JASON*", "ou *TIME LUCIA*?", "quem é mais *DAORA*?"], "image": "jason_car"},
    ],
},
{
    "slug": "bonnie_e_clyde",
    "title_hook": "BONNIE & CLYDE MODERNOS",
    "cta": ("BONNIE & CLYDE?", "COMENTA!"),
    "segments": [
        {"kind": "hook", "narration": "Bonnie e Clyde da era moderna? A dupla de GTA 6 esconde muito mais camadas!",
         "captions": ["*LUCIA* e *JASON*:", "os *BONNIE E CLYDE*", "da era *MODERNA*?"], "image": "assalto"},
        {"kind": "fact", "title": "BONNIE & CLYDE",
         "narration": "Lucia e Jason vivem sendo comparados a Bonnie e Clyde, o famoso casal criminoso dos anos trinta.",
         "captions": ["Comparados a", "*BONNIE E CLYDE*", "o casal criminoso", "dos anos *30*"], "image": "assalto"},
        {"kind": "fact", "title": "ROCKSTAR NUNCA DISSE ISSO",
         "narration": "Mas a Rockstar nunca usou essas palavras. A comparação veio da mídia e dos fãs.",
         "captions": ["Mas a *ROCKSTAR*", "*NUNCA* usou", "essas *PALAVRAS*"], "image": "danca"},
        {"kind": "fact", "title": "O BARALHO CONTRA ELES",
         "narration": "A frase oficial da dupla é: eles sempre souberam que o baralho estava contra eles.",
         "captions": ["A frase oficial:", "\"o *BARALHO*", "está *CONTRA* eles\""], "image": "noite"},
        {"kind": "fact", "title": "JUNTOS, SEMPRE",
         "narration": "No trailer, Lucia diz que o único jeito de passar por isso é juntos, sendo um time.",
         "captions": ["Lucia diz:", "\"o único jeito é", "*JUNTOS*, sendo", "um *TIME*\""], "image": "danca_n"},
        {"kind": "fact", "title": "LOVE IS A LONG ROAD",
         "narration": "A música do primeiro trailer é Love Is a Long Road, do Tom Petty. Uma pista e tanto.",
         "captions": ["A música do trailer:", "\"*LOVE IS*", "*A LONG ROAD*\"", "do *TOM PETTY*"], "image": "vc_noite"},
        {"kind": "fact", "title": "O FIM REAL DA DUPLA",
         "narration": "Bonnie e Clyde de verdade morreram em 1934, numa emboscada da polícia na Louisiana.",
         "captions": ["Os reais morreram", "em *1934*", "numa *EMBOSCADA*", "na *LOUISIANA*"], "image": "assalto"},
        {"kind": "fact", "title": "MAIS QUE ROMANCE",
         "narration": "Mas, diferente deles, a história de Lucia e Jason foca em confiança e sobrevivência, não só romance.",
         "captions": ["Aqui o foco é", "*CONFIANÇA*", "e *SOBREVIVÊNCIA*", "não só *ROMANCE*"], "image": "danca"},
        {"kind": "cta", "narration": "Curtiu essa vibe Bonnie e Clyde? Deixa o like e comenta!",
         "captions": ["Curtiu a vibe", "*BONNIE E CLYDE*?", "deixa o *LIKE*!"], "image": "danca_n"},
    ],
},
{
    "slug": "dois_protagonistas",
    "title_hook": "DOIS PROTAGONISTAS JOGÁVEIS",
    "cta": ("QUAL SEU FAVORITO?", "COMENTA!"),
    "segments": [
        {"kind": "hook", "narration": "Pela primeira vez em um GTA principal, você joga com uma dupla de verdade. Entenda!",
         "captions": ["*GTA 6* tem", "uma *DUPLA*", "de *PROTAGONISTAS*!"], "image": "danca"},
        {"kind": "fact", "title": "DOIS JOGÁVEIS",
         "narration": "GTA 6 tem dois protagonistas jogáveis: Lucia e Jason.",
         "captions": ["*DOIS* protagonistas", "*JOGÁVEIS*:", "*LUCIA* e *JASON*"], "image": "danca"},
        {"kind": "fact", "title": "TROCA COMO NO GTA 5",
         "narration": "A troca entre eles deve funcionar como no GTA 5: aperta pra baixo no D-Pad e alterna.",
         "captions": ["A *TROCA* funciona", "como no *GTA 5*:", "aperta pra *BAIXO*", "no *D-PAD*"], "image": "jason_car"},
        {"kind": "fact", "title": "LUCIA: ÁGIL E FURTIVA",
         "narration": "Segundo análises do trailer, Lucia tem um estilo mais ágil e furtivo.",
         "captions": ["*LUCIA* tem estilo", "mais *ÁGIL*", "e *FURTIVO*"], "image": "lucia_tre"},
        {"kind": "fact", "title": "JASON: FORÇA BRUTA",
         "narration": "Jason, por outro lado, é a força bruta: resistente e bom no corpo a corpo.",
         "captions": ["*JASON* é a", "*FORÇA BRUTA*:", "resistente e", "bom no *CORPO A CORPO*"], "image": "jason_car"},
        {"kind": "fact", "title": "UMA HISTÓRIA, DOIS OLHARES",
         "narration": "Diferente do GTA 5, aqui os dois são um casal. Uma história só, vivida por dois pontos de vista.",
         "captions": ["Os dois são", "um *CASAL*", "uma *HISTÓRIA* só", "dois *PONTOS DE VISTA*"], "image": "danca_n"},
        {"kind": "fact", "title": "ENCONTRO NA CONDICIONAL",
         "narration": "Lucia conhece Jason por causa de um programa de liberdade condicional.",
         "captions": ["Lucia conhece *JASON*", "num programa de", "*CONDICIONAL*"], "image": "noite"},
        {"kind": "fact", "title": "PARCEIROS COMPLETOS",
         "narration": "Juntos, eles cobrem as fraquezas um do outro. Parceria de verdade.",
         "captions": ["Juntos, eles cobrem", "as *FRAQUEZAS*", "um do *OUTRO*"], "image": "danca"},
        {"kind": "cta", "narration": "Jogar com os dois vai ser demais! Qual você acha que vai ser teu favorito?",
         "captions": ["*JOGAR* com os dois", "vai ser *DEMAIS*!"], "image": "noite"},
    ],
},
{
    "slug": "passado_sombrio",
    "title_hook": "O PASSADO SOMBRIO",
    "cta": ("QUAL PASSADO INTRIGA MAIS?", "COMENTA!"),
    "segments": [
        {"kind": "hook", "narration": "Antes do golpe que muda tudo, Lucia e Jason já carregavam um passado bem pesado.",
         "captions": ["O *PASSADO*", "de *LUCIA* e *JASON*", "é *PESADO*"], "image": "noite"},
        {"kind": "fact", "title": "CRIME NÃO REVELADO",
         "narration": "Lucia saiu da prisão por pura sorte, e o crime exato dela nunca foi revelado.",
         "captions": ["Ela saiu por", "*PURA SORTE*", "e o crime exato", "*NUNCA* foi revelado"], "image": "lucia_din"},
        {"kind": "fact", "title": "LUTOU PELA FAMÍLIA",
         "narration": "Ela lutou pela família a vida inteira, e foi isso que a levou à Penitenciária de Leonida.",
         "captions": ["Lutou pela *FAMÍLIA*", "e foi parar na", "Penitenciária de", "*LEONIDA*"], "image": "lucia_din"},
        {"kind": "fact", "title": "SOLDADO ANTES DO CRIME",
         "narration": "Jason foi soldado do exército antes de cair de vez no mundo do crime.",
         "captions": ["*JASON* foi", "*SOLDADO*", "antes de cair", "no *CRIME*"], "image": "jason_car"},
        {"kind": "fact", "title": "NAS KEYS",
         "narration": "Nas Keys, ele trabalhava pra traficantes, fazendo o que sabia fazer de melhor.",
         "captions": ["Nas *KEYS*, ele", "trabalhava pra", "*TRAFICANTES*"], "image": "keys"},
        {"kind": "fact", "title": "TREINO DESDE CRIANÇA",
         "narration": "O pai de Lucia treinou ela pra lutar desde que era criança.",
         "captions": ["O *PAI* treinou ela", "pra *LUTAR*", "desde *CRIANÇA*"], "image": "lucia_tre"},
        {"kind": "fact", "title": "RAÍZES EM LIBERTY CITY",
         "narration": "As raízes da família dela estão em Liberty City, longe de Leonida.",
         "captions": ["As *RAÍZES* dela", "estão em", "*LIBERTY CITY*"], "image": "vc_noite"},
        {"kind": "fact", "title": "COMEÇO PEQUENO",
         "narration": "Os dois começaram com assaltos pequenos, como a loja Uncle Jack's Liquor.",
         "captions": ["Começaram com", "*ASSALTOS PEQUENOS*", "como a", "*UNCLE JACK'S*"], "image": "assalto"},
        {"kind": "cta", "narration": "Qual passado te intriga mais? O da Lucia ou o do Jason? Comenta!",
         "captions": ["Qual *PASSADO*", "te *INTRIGA* mais?", "o da *LUCIA* ou do *JASON*?"], "image": "assalto"},
    ],
},
{
    "slug": "leonida_vice_city",
    "title_hook": "LEONIDA & VICE CITY",
    "cta": ("QUAL CANTO DE LEONIDA?", "COMENTA!"),
    "segments": [
        {"kind": "hook", "narration": "GTA 6 se passa em Leonida, a Flórida fictícia da Rockstar. E tem muita coisa escondida!",
         "captions": ["*LEONIDA*:", "a *FLÓRIDA*", "fictícia da *ROCKSTAR*"], "image": "vc_noite"},
        {"kind": "fact", "title": "ESTADO DE LEONIDA",
         "narration": "O jogo se passa no estado de Leonida, claramente inspirado na Flórida.",
         "captions": ["O jogo se passa", "em *LEONIDA*", "inspirado na", "*FLÓRIDA*"], "image": "vc_noite"},
        {"kind": "fact", "title": "VICE CITY = MIAMI",
         "narration": "Vice City, a versão da Rockstar pra Miami, é o coração da história.",
         "captions": ["*VICE CITY*", "é a versão de", "*MIAMI*", "da *ROCKSTAR*"], "image": "vc_noite"},
        {"kind": "fact", "title": "LOCAL X FORASTEIRA",
         "narration": "Jason é nativo de Leonida, das Keys. Já Lucia veio de Liberty City.",
         "captions": ["*JASON* é das *KEYS*", "*LUCIA* veio de", "*LIBERTY CITY*"], "image": "keys"},
        {"kind": "fact", "title": "ASSALTO À UNCLE JACK'S",
         "narration": "No trailer, os dois assaltam juntos a loja Uncle Jack's Liquor.",
         "captions": ["No trailer, assaltam", "a *UNCLE JACK'S*", "*LIQUOR*"], "image": "assalto"},
        {"kind": "fact", "title": "DECLASSE TULIP",
         "narration": "O carro dos dois nas fugas é um clássico Declasse Tulip.",
         "captions": ["O carro deles?", "um *DECLASSE*", "*TULIP* clássico"], "image": "jason_car"},
        {"kind": "fact", "title": "ACADEMIA, MOTO E NEON",
         "narration": "As cenas mostram de tudo: academia de boxe, moto, baladas e muito neon.",
         "captions": ["Tem *ACADEMIA*", "*MOTO*, *BALADAS*", "e muito *NEON*"], "image": "danca_n"},
        {"kind": "fact", "title": "ESTILO FLÓRIDA",
         "narration": "Leonida é cheia de personagens doidos, no melhor estilo Flórida de verdade.",
         "captions": ["Personagens *DOIDOS*", "no melhor estilo", "*FLÓRIDA* real"], "image": "vc_noite"},
        {"kind": "cta", "narration": "Ansioso pra explorar Leonida? Comenta qual canto você quer ver primeiro!",
         "captions": ["*ANSIOU* pra explorar", "*LEONIDA*?"], "image": "danca_n"},
    ],
},
{
    "slug": "recordes_bastidores",
    "title_hook": "RECORDES & BASTIDORES",
    "cta": ("CONTANDO OS DIAS?", "COMENTA!"),
    "segments": [
        {"kind": "hook", "narration": "GTA 6 já quebrou recordes antes mesmo de lançar. Olha essas curiosidades de bastidor!",
         "captions": ["*GTA 6* quebrou", "*RECORDES*", "antes de *LANÇAR*"], "image": "vc_noite"},
        {"kind": "fact", "title": "TRAILER RECORDE",
         "narration": "O primeiro trailer, em dezembro de 2023, bateu recorde de visualizações no YouTube.",
         "captions": ["O trailer de *2023*", "bateu *RECORDE*", "no *YOUTUBE*"], "image": "vc_noite"},
        {"kind": "fact", "title": "TOM PETTY VOLTOU A BOMBAR",
         "narration": "A música do trailer, Love Is a Long Road do Tom Petty, voltou a bombar depois de décadas.",
         "captions": ["\"*LOVE IS*", "*A LONG ROAD*\"", "do *TOM PETTY*", "voltou a *BOMBAR*"], "image": "danca_n"},
        {"kind": "fact", "title": "MARCO NA FRANQUIA",
         "narration": "Lucia é a primeira protagonista feminina dublada da franquia principal.",
         "captions": ["*LUCIA* é a primeira", "protagonista *FEMININA*", "*DUBLADA* da franquia"], "image": "lucia_din"},
        {"kind": "fact", "title": "19 DE NOVEMBRO DE 2026",
         "narration": "O jogo chega em 19 de novembro de 2026.",
         "captions": ["O jogo chega em", "*19 DE NOVEMBRO*", "de *2026*"], "image": "noite"},
        {"kind": "fact", "title": "PC VEM DEPOIS",
         "narration": "Primeiro sai pra consoles. A versão de PC deve chegar depois, em 2027 ou 2028.",
         "captions": ["*CONSOLES* primeiro", "*PC* depois:", "*2027* ou *2028*"], "image": "keys"},
        {"kind": "fact", "title": "MODO ONLINE CONFIRMADO",
         "narration": "A Rockstar confirmou que vai ter modo online, seguindo o sucesso do GTA Online.",
         "captions": ["*MODO ONLINE*", "*CONFIRMADO* pela", "*ROCKSTAR*"], "image": "vc_noite"},
        {"kind": "fact", "title": "NOMES REVELADOS",
         "narration": "Os nomes Lucia Caminos e Jason Duval foram revelados aos poucos, nos trailers.",
         "captions": ["*LUCIA CAMINOS*", "e *JASON DUVAL*", "revelados nos", "*TRAILERS*"], "image": "danca"},
        {"kind": "cta", "narration": "Contando os dias pro dia 19 de novembro? Comenta aí!",
         "captions": ["*CONTANDO* os dias", "pro dia *19*?"], "image": "noite"},
    ],
},
{
    "slug": "detalhes_escondidos",
    "title_hook": "DETALHES ESCONDIDOS",
    "cta": ("VIU OUTRO DETALHE?", "COMENTA!"),
    "segments": [
        {"kind": "hook", "narration": "Tem detalhes escondidos em GTA 6 que quase ninguém reparou. Vem ver!",
         "captions": ["*DETALHES*", "escondidos em *GTA 6*", "que *NINGUÉM* viu"], "image": "danca_n"},
        {"kind": "fact", "title": "APELIDO: LU LU",
         "narration": "O apelido de Lucia, usado pelo Jason, é Lu Lu.",
         "captions": ["O apelido da *LUCIA*", "usado pelo *JASON*", "é *LU LU*"], "image": "lucia_din"},
        {"kind": "fact", "title": "FOTO NA CELA",
         "narration": "Na cela dela tem uma foto de família, uma pista de vida além do crime.",
         "captions": ["Na cela, uma", "*FOTO DE FAMÍLIA*", "pista de vida", "além do *CRIME*"], "image": "lucia_din"},
        {"kind": "fact", "title": "A ASSISTENTE STEFANIE",
         "narration": "A assistente social da Lucia na prisão se chama Stefanie.",
         "captions": ["A *ASSISTENTE*", "social da *LUCIA*", "se chama *STEFANIE*"], "image": "noite"},
        {"kind": "fact", "title": "JASON PESCADOR",
         "narration": "Jason pesca com o amigo Cal nas Keys, um lado tranquilo raro no GTA.",
         "captions": ["*JASON* pesca", "com o amigo *CAL*", "nas *KEYS*"], "image": "keys"},
        {"kind": "fact", "title": "LUCIA ABRE E FECHA",
         "narration": "O trailer abre e fecha com a Lucia, mostrando que ela é o fio da história.",
         "captions": ["O trailer *ABRE*", "e *FECHA* com", "a *LUCIA*"], "image": "danca_n"},
        {"kind": "fact", "title": "LUCIA E SADIE ADLER",
         "narration": "Lucia tem semelhanças com a Sadie Adler, de Red Dead Redemption 2.",
         "captions": ["*LUCIA* lembra a", "*SADIE ADLER*", "de *RED DEAD 2*"], "image": "lucia_tre"},
        {"kind": "fact", "title": "SEMPRE JUNTOS",
         "narration": "A dupla aparece junta em quase todas as cenas do trailer, sempre como um time.",
         "captions": ["Os dois aparecem", "*SEMPRE JUNTOS*", "em quase todas", "as *CENAS*"], "image": "danca"},
        {"kind": "cta", "narration": "Notou algum outro detalhe? Manda nos comentários!",
         "captions": ["Notou algum", "outro *DETALHE*?", "manda nos *COMENTÁRIOS*!"], "image": "danca"},
    ],
},
]
